import type { AuditResult, Finding, MarkerPoint } from "@/lib/audit";

const FALLBACK_MODELS = ["gemini-3.1-flash-lite", "gemini-3.5-flash-lite", "gemini-2.5-flash-lite"];
function clamp(v:number,min:number,max:number){return Math.min(max,Math.max(min,v));}
function extractJson(text:string):unknown|null{const cleaned=text.replace(/```json/gi,"").replace(/```/g,"").trim();try{return JSON.parse(cleaned)}catch{}const start=cleaned.indexOf("{");if(start<0)return null;let depth=0,inString=false,escaped=false;for(let i=start;i<cleaned.length;i+=1){const ch=cleaned[i];if(inString){if(escaped)escaped=false;else if(ch==="\\")escaped=true;else if(ch==='"')inString=false;continue}if(ch==='"'){inString=true;continue}if(ch==="{")depth+=1;if(ch==="}"){depth-=1;if(depth===0){try{return JSON.parse(cleaned.slice(start,i+1))}catch{return null}}}}return null}
async function generate(apiKey:string,parts:Array<Record<string,unknown>>){for(const model of FALLBACK_MODELS){const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","X-goog-api-key":apiKey},body:JSON.stringify({contents:[{role:"user",parts}],generationConfig:{responseMimeType:"application/json",maxOutputTokens:1400,temperature:.02}}),signal:AbortSignal.timeout(20000)});if(r.ok){const p:any=await r.json();const t=(p?.candidates?.[0]?.content?.parts??[]).map((x:any)=>typeof x?.text==="string"?x.text:"").join("");if(t)return t}}throw new Error("Mobile marker verification failed")}
function parseMarkers(parsed:unknown){const root=parsed&&typeof parsed==="object"?parsed as Record<string,unknown>:{};const out=new Map<string,MarkerPoint>();for(const raw of Array.isArray(root.markers)?root.markers:[]){if(!raw||typeof raw!=="object")continue;const x=raw as Record<string,unknown>;if(typeof x.id!=="string")continue;const px=Number(x.x),py=Number(x.y);if(!Number.isFinite(px)||!Number.isFinite(py))continue;out.set(x.id,{x:clamp(px/1000,.02,.98),y:clamp(py/1000,.02,.98)})}return out}

export async function calibrateMobileMarkers(apiKey:string,result:AuditResult,screenshot:Buffer,mimeType="image/png"):Promise<AuditResult>{const entries=result.pages.flatMap(page=>page.viewMode==="mobile"?page.findings.map(finding=>({finding,page})):[]);if(!entries.length)return result;const imageBase64=screenshot.toString("base64"),updated=new Map<string,MarkerPoint>();
 for(let start=0;start<entries.length;start+=2){const batch=entries.slice(start,start+2);const targets=batch.map(({finding},i)=>({id:finding.id||`finding-${start+i+1}`,title:finding.title,category:finding.category,description:finding.description,evidenceElement:finding.evidence[0]?.element??"",evidenceDetail:finding.evidence[0]?.detail??""}));const prompt=`You are the FINAL SPATIAL VERIFICATION stage of a mobile UX audit. The image is the COMPLETE ORIGINAL mobile-responsive webpage. Existing findings are approved. Your ONLY task is to locate the exact visible UI element that each finding refers to and return its marker coordinate.\n\nInspect the entire image from top to bottom. Do not estimate vertical position from section names, page proportions, or the finding order. Do not place a marker in empty space. If the evidence is an accordion, button, input, card, text block, image, navigation item, badge, or other control, place the point directly ON that element, ideally at its visual centre.\n\nCoordinates are integers 0-1000 relative to the COMPLETE ORIGINAL IMAGE: x=0 left, x=1000 right, y=0 top, y=1000 bottom. Return exactly one marker per target. Do not rewrite findings.\n\nReturn JSON only: {"markers":[{"id":"finding-id","x":500,"y":240}]}\n\nTARGETS:\n${JSON.stringify(targets)}`;try{const text=await generate(apiKey,[{inline_data:{mime_type:mimeType,data:imageBase64}},{text:prompt}]);parseMarkers(extractJson(text)).forEach((marker,id)=>updated.set(id,marker))}catch{}}
 if(!updated.size)return result;return {...result,pages:result.pages.map(page=>page.viewMode!=="mobile"?page:{...page,findings:page.findings.map((finding)=>{const marker=updated.get(finding.id);if(!marker||!finding.evidence.length)return finding;return {...finding,evidence:finding.evidence.map((e,i)=>i===0?{...e,marker}:e)}})})};}
