"use client";
import { useEffect, useMemo, useState } from "react";
import type { Finding } from "@/lib/audit";
import styles from "./knowledge-base.module.css";

type Client={id:string;name:string;created_at:string;updated_at:string};
type Audit={id:string;client_id:string;client_name:string;title:string;source_filename:string;created_at:string;screenshot_width:number;screenshot_height:number;view_mode?:string;report_generated_at?:string|null};
type StoredFinding={id:string;finding_index:number;finding:Finding;created_at:string};
type AuditDetail=Audit&{screenshot:string;report_html?:string|null;findings:StoredFinding[]};
const colors=["pink","purple","orange","blue","green","yellow","violet","teal","rose","cyan"];
const date=(v:string)=>new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const view=(v?:string)=>v==="mobile"?"Mobile responsive":v==="tablet"?"Tablet":v==="desktop"?"Desktop web":"View mode unknown";

export default function KnowledgeBaseClient(){
 const [clients,setClients]=useState<Client[]>([]),[audits,setAudits]=useState<Audit[]>([]),[audit,setAudit]=useState<AuditDetail|null>(null),[selected,setSelected]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[client,setClient]=useState<Client|null>(null),[generating,setGenerating]=useState<string|null>(null);
 async function loadClients(){setLoading(true);setError("");setClient(null);setAudits([]);setAudit(null);try{const r=await fetch("/api/knowledge-base",{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error);setClients(d.clients||[])}catch(e){setError(e instanceof Error?e.message:"Could not load the knowledge base.")}finally{setLoading(false)}}
 async function openClient(c:Client){setClient(c);setAudit(null);setSelected(0);setLoading(true);setError("");try{const r=await fetch(`/api/knowledge-base?clientId=${encodeURIComponent(c.id)}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw Error(d.error);setAudits(d.audits||[])}catch(e){setError(e instanceof Error?e.message:"Could not load audits.")}finally{setLoading(false)}}
 async function openAudit(a:Audit){setAudit(null);setSelected(0);setLoading(true);setError("");try{const r=await fetch(`/api/knowledge-base?auditId=${encodeURIComponent(a.id)}`,{cache:"no-store"}),d=await r.json();if(!r.ok||!d.audit)throw Error(d.error);setAudit(d.audit)}catch(e){setError(e instanceof Error?e.message:"Could not load the analysis.")}finally{setLoading(false)}}
 async function generateReport(a:Audit){if(generating)return;setGenerating(a.id);setError("");try{const r=await fetch("/api/report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({auditId:a.id})}),d=await r.json();if(!r.ok)throw Error(d.error);setAudits(x=>x.map(i=>i.id===a.id?{...i,report_generated_at:d.generatedAt}:i));window.open(d.reportUrl,"_blank","noopener,noreferrer")}catch(e){setError(e instanceof Error?e.message:"Could not generate the client report.")}finally{setGenerating(null)}}
 useEffect(()=>{void loadClients()},[]);
 const finding=audit?.findings[selected]?.finding;const high=useMemo(()=>audit?.findings.filter(x=>x.finding.severity==="high").length||0,[audit]);
 return <main className={styles.shell}><header className={styles.nav}><a href="/" className={styles.brand}>UX Audit <span>by ScreenRoot</span></a><a href="/" className={styles.back}>← New audit</a></header>
 <section className={styles.hero}><div><div className={styles.eyebrow}>Knowledge base</div><h1>Client findings, kept in one place.</h1><p>Browse completed audits by client and create the polished client report directly from the audit history.</p></div><div className={styles.stat}><b>{clients.length}</b><span>clients</span></div></section>
 {error&&<div className={styles.error}>{error}</div>}{loading&&<div className={styles.loading}>Loading knowledge base…</div>}
 {!loading&&!client&&<section className={styles.content}><div className={styles.sectionHead}><div><small>Clients</small><h2>Choose a client</h2></div><span>{clients.length} total</span></div><div className={styles.clientGrid}>{clients.map(c=><button className={styles.clientCard} key={c.id} onClick={()=>void openClient(c)}><i>{c.name.slice(0,1).toUpperCase()}</i><div><b>{c.name}</b><small>View audit history →</small></div></button>)}{!clients.length&&<div className={styles.empty}>No audits have been stored yet.</div>}</div></section>}
 {!loading&&client&&!audit&&<section className={styles.content}><button className={styles.crumb} onClick={()=>void loadClients()}>← All clients</button><div className={styles.sectionHead}><div><small>Client</small><h2>{client.name}</h2></div><span>{audits.length} audits</span></div><div className={styles.auditList}>{audits.map(a=><article className={styles.auditRow} key={a.id}><button className={styles.auditMain} onClick={()=>void openAudit(a)}><strong>{new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short"}).format(new Date(a.created_at))}</strong><div><b>{a.title}</b><small>{date(a.created_at)} · {a.screenshot_width} × {a.screenshot_height}px · {view(a.view_mode)}</small></div></button><div className={styles.actions}><button className={styles.open} onClick={()=>void openAudit(a)}>Open analysis</button>{a.report_generated_at?<a className={`${styles.report} ${styles.generated}`} href={`/report/${encodeURIComponent(a.id)}`} target="_blank" rel="noreferrer">↗ View report</a>:<button className={styles.report} onClick={()=>void generateReport(a)} disabled={!!generating}>{generating===a.id?<><i/>Generating…</>:<>✦ Generate report</>}</button>}</div></article>)}{!audits.length&&<div className={styles.empty}>No audits found for this client.</div>}</div></section>}
 {!loading&&audit&&<section className={styles.content}><button className={styles.crumb} onClick={()=>{setAudit(null);setSelected(0)}}>← {client?.name||"Client history"}</button><div className={styles.analysisHead}><div><small>Audit analysis</small><h2>{audit.client_name}</h2><p>{date(audit.created_at)} · {audit.source_filename} · {view(audit.view_mode)}</p></div><div><b>{audit.findings.length}</b><small>findings</small><em>{high} high priority</em></div></div><div className={styles.analysis}><aside><small>Findings</small>{audit.findings.map((x,i)=><button key={x.id} className={selected===i?styles.active:""} onClick={()=>setSelected(i)}><i className={styles[colors[i%colors.length]]}>{i+1}</i><span><b>{x.finding.title}</b><small>{x.finding.category} · {x.finding.severity}</small></span></button>)}</aside><div className={styles.detail}>{finding&&<><div className={styles.meta}><b>{finding.severity}</b><span>{finding.category}</span></div><h2>{finding.title}</h2><p className={styles.description}>{finding.description}</p><div className={styles.evidence}><i className={styles[colors[selected%colors.length]]}>{selected+1}</i><div><b>{finding.evidence[0]?.element||"Analysed region"}</b><small>{finding.evidence[0]?.section||"Page section"} · {finding.evidence[0]?.detail||"Visible evidence from the original screenshot."}</small></div></div><div className={styles.grids}><section><small>UX principle</small><h3>{finding.uxPerspective.law}</h3><p><b>Definition:</b> {finding.uxPerspective.definition}</p><p><b>Why it applies:</b> {finding.uxPerspective.assessment}</p><p><b>Research context:</b> {finding.uxPerspective.researchContext}</p></section><section><small>Business analysis</small><h3>{finding.businessAnalysis.funnelStage}</h3><p><b>Impact:</b> {finding.businessAnalysis.impact}</p><p><b>KPI at risk:</b> {finding.businessAnalysis.kpi}</p><p><b>Mechanism:</b> {finding.businessAnalysis.mechanism}</p><ul>{finding.businessAnalysis.suggestions.map(s=><li key={s}>{s}</li>)}</ul></section></div><div className={styles.recommend}><b>Recommended redesign:</b> {finding.recommendation}</div><div className={styles.screen}><header><div><small>Evidence map</small><h3>Original analysed screenshot</h3></div><span>Finding {selected+1} of {audit.findings.length}</span></header><div className={styles.canvas}><img src={audit.screenshot} alt={`Original ${audit.client_name} screenshot`}/>{audit.findings.map((x,i)=>{const m=x.finding.evidence[0]?.marker;return m?<button key={x.id} className={`${styles.marker} ${styles[colors[i%colors.length]]} ${selected===i?styles.markerSelected:""}`} style={{left:`${m.x*100}%`,top:`${m.y*100}%`}} onClick={()=>setSelected(i)}>{i+1}</button>:null})}</div></div></>}</div></div></section>}
 </main>;
}
