"use client";
import { useEffect, useMemo, useState } from "react";
import type { Finding } from "@/lib/audit";
import styles from "./knowledge-base.module.css";

type Client = { id: string; name: string; created_at: string; updated_at: string };
type AuditPageSummary = { id: string; page_name: string; source_filename: string; view_mode?: string };
type Audit = { id: string; client_id: string; client_name: string; title: string; source_filename: string; created_at: string; screenshot_width: number; screenshot_height: number; view_mode?: string; report_generated_at?: string | null; audit_pages?: AuditPageSummary[] };
type StoredFinding = { id: string; page_id?: string; finding_index: number; finding: Finding; created_at: string };
type AuditPage = { id: string; auditId: string; clientName: string; viewMode?: string; title: string; screenshot: string; screenshotWidth: number; screenshotHeight: number; findings: Finding[] };
type AuditDetail = Audit & { screenshot: string; report_html?: string | null; findings: StoredFinding[]; pages: AuditPage[] };
const colors = ["pink", "purple", "orange", "blue", "green", "yellow", "violet", "teal", "rose", "cyan"];
const date = (v: string) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(v));
const view = (v?: string) => v === "mobile" ? "Mobile responsive" : v === "tablet" ? "Tablet" : v === "desktop" ? "Desktop web" : "View mode unknown";

export default function KnowledgeBaseClient() {
  const [clients, setClients] = useState<Client[]>([]), [audits, setAudits] = useState<Audit[]>([]), [audit, setAudit] = useState<AuditDetail | null>(null), [selected, setSelected] = useState(0), [selectedPage, setSelectedPage] = useState(0), [loading, setLoading] = useState(true), [error, setError] = useState(""), [client, setClient] = useState<Client | null>(null), [generating, setGenerating] = useState<string | null>(null), [deleting, setDeleting] = useState<string | null>(null);

  async function loadClients() { setLoading(true); setError(""); setClient(null); setAudits([]); setAudit(null); try { const r = await fetch("/api/knowledge-base", { cache: "no-store" }), d = await r.json(); if (!r.ok) throw Error(d.error); setClients(d.clients || []); } catch (e) { setError(e instanceof Error ? e.message : "Could not load the knowledge base."); } finally { setLoading(false); } }
  async function openClient(c: Client) { setClient(c); setAudit(null); setSelected(0); setSelectedPage(0); setLoading(true); setError(""); try { const r = await fetch(`/api/knowledge-base?clientId=${encodeURIComponent(c.id)}`, { cache: "no-store" }), d = await r.json(); if (!r.ok) throw Error(d.error); setAudits(d.audits || []); } catch (e) { setError(e instanceof Error ? e.message : "Could not load audits."); } finally { setLoading(false); } }
  async function openAudit(a: Audit) { setAudit(null); setSelected(0); setSelectedPage(0); setLoading(true); setError(""); try { const r = await fetch(`/api/knowledge-base?auditId=${encodeURIComponent(a.id)}`, { cache: "no-store" }), d = await r.json(); if (!r.ok || !d.audit) throw Error(d.error); setAudit(d.audit); } catch (e) { setError(e instanceof Error ? e.message : "Could not load the analysis."); } finally { setLoading(false); } }
  async function generateReport(a: Audit) { if (generating) return; setGenerating(a.id); setError(""); try { const r = await fetch("/api/report", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ auditId: a.id }) }), d = await r.json(); if (!r.ok) throw Error(d.error); setAudits((x) => x.map((i) => i.id === a.id ? { ...i, report_generated_at: d.generatedAt } : i)); window.open(d.reportUrl, "_blank", "noopener,noreferrer"); } catch (e) { setError(e instanceof Error ? e.message : "Could not generate the client report."); } finally { setGenerating(null); } }
  async function removeAudit(a: Audit) { if (deleting) return; const confirmed = window.confirm(`Delete this audit from ${a.client_name}? This permanently removes the audit, its pages, findings and stored report from the database.`); if (!confirmed) return; setDeleting(a.id); setError(""); try { const r = await fetch("/api/knowledge-base", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ auditId: a.id }) }), d = await r.json(); if (!r.ok) throw Error(d.error); const remaining = audits.filter((item) => item.id !== a.id); setAudits(remaining); if (!remaining.length) { setClient(null); setAudit(null); await loadClients(); } else if (audit?.id === a.id) setAudit(null); } catch (e) { setError(e instanceof Error ? e.message : "Could not delete the audit."); } finally { setDeleting(null); } }
  useEffect(() => { void loadClients(); }, []);

  const page = audit?.pages[selectedPage];
  const finding = page?.findings[selected];
  const high = useMemo(() => page?.findings.filter((x) => x.severity === "high").length || 0, [page]);
  const totalHigh = useMemo(() => audit?.pages.reduce((sum, item) => sum + item.findings.filter((x) => x.severity === "high").length, 0) || 0, [audit]);
  function selectPage(index: number) { setSelectedPage(index); setSelected(0); }

  return <main className={styles.shell}>
    <header className={styles.nav}><a href="/" className={styles.brand}>UX Audit <span>by ScreenRoot</span></a><a href="/" className={styles.back}>← New audit</a></header>
    <section className={styles.hero}><div><div className={styles.eyebrow}>Knowledge base</div><h1>Client findings, kept in one place.</h1><p>Browse timestamped audit runs by client. A single run can contain multiple website pages, each preserved as its own tab and evidence map.</p></div><div className={styles.stat}><b>{clients.length}</b><span>clients</span></div></section>
    {error && <div className={styles.error}>{error}</div>}{loading && <div className={styles.loading}>Loading knowledge base…</div>}

    {!loading && !client && <section className={styles.content}><div className={styles.sectionHead}><div><small>Clients</small><h2>Choose a client</h2></div><span>{clients.length} total</span></div><div className={styles.clientGrid}>{clients.map((c) => <button className={styles.clientCard} key={c.id} onClick={() => void openClient(c)}><i>{c.name.slice(0, 1).toUpperCase()}</i><div><b>{c.name}</b><small>View audit history →</small></div></button>)}{!clients.length && <div className={styles.empty}>No audits have been stored yet.</div>}</div></section>}

    {!loading && client && !audit && <section className={styles.content}><button className={styles.crumb} onClick={() => void loadClients()}>← All clients</button><div className={styles.sectionHead}><div><small>Client</small><h2>{client.name}</h2></div><span>{audits.length} audit runs</span></div><div className={styles.auditList}>{audits.map((a) => <article className={styles.auditRow} key={a.id}><button className={styles.auditMain} onClick={() => void openAudit(a)}><strong>{new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short" }).format(new Date(a.created_at))}</strong><div><b>{a.title}</b><small>{date(a.created_at)} · {a.audit_pages?.length || 1} page{(a.audit_pages?.length || 1) === 1 ? "" : "s"} · {a.report_generated_at ? "Report ready" : "Report not generated"}</small></div></button><div className={styles.actions}><button className={styles.open} onClick={() => void openAudit(a)}>Open analysis</button>{a.report_generated_at ? <a className={`${styles.report} ${styles.generated}`} href={`/report/${encodeURIComponent(a.id)}`} target="_blank" rel="noreferrer">↗ View report</a> : <button className={styles.report} onClick={() => void generateReport(a)} disabled={!!generating}>{generating === a.id ? <><i />Generating…</> : <>✦ Generate report</>}</button>}<button className={styles.open} style={{ color: "#9b2f2f", borderColor: "#e7c9c9", background: "#fff8f7" }} onClick={() => void removeAudit(a)} disabled={deleting === a.id}>{deleting === a.id ? "Deleting…" : "Delete"}</button></div></article>)}{!audits.length && <div className={styles.empty}>No audits found for this client.</div>}</div></section>}

    {!loading && audit && page && <section className={styles.content}><button className={styles.crumb} onClick={() => { setAudit(null); setSelected(0); setSelectedPage(0); }}>← {client?.name || "Client history"}</button><div className={styles.analysisHead}><div><small>Audit run</small><h2>{audit.client_name}</h2><p>{date(audit.created_at)} · {audit.pages.length} pages · {audit.source_filename}</p></div><div><b>{audit.findings.length}</b><small>findings</small><em>{totalHigh} high priority across run</em></div></div>
      <div className={styles.pageTabs} role="tablist" aria-label="Audit pages">{audit.pages.map((item, index) => <button key={item.id} className={selectedPage === index ? styles.pageTabActive : styles.pageTab} onClick={() => selectPage(index)} role="tab" aria-selected={selectedPage === index}><span>{item.title}</span><small>{item.findings.filter((x) => x.severity === "high").length} high · {item.findings.length} total</small></button>)}</div>
      <div className={styles.analysis}><aside><small>Findings · {page.title}</small>{page.findings.map((x, i) => <button key={x.id} className={selected === i ? styles.active : ""} onClick={() => setSelected(i)}><i className={styles[colors[i % colors.length]]}>{i + 1}</i><span><b>{x.title}</b><small>{x.category} · {x.severity}</small></span></button>)}{!page.findings.length && <div style={{ padding: 12, color: "#777", fontSize: 12 }}>No findings for this page.</div>}</aside><div className={styles.detail}>{finding ? <><div className={styles.meta}><b>{finding.severity}</b><span>{finding.category}</span></div><h2>{finding.title}</h2><p className={styles.description}>{finding.description}</p><div className={styles.evidence}><i className={styles[colors[selected % colors.length]]}>{selected + 1}</i><div><b>{finding.evidence[0]?.element || "Analysed region"}</b><small>{finding.evidence[0]?.section || "Page section"} · {finding.evidence[0]?.detail || "Visible evidence from the original screenshot."}</small></div></div><div className={styles.grids}><section><small>UX principle</small><h3>{finding.uxPerspective.law}</h3><p><b>Definition:</b> {finding.uxPerspective.definition}</p><p><b>Why it applies:</b> {finding.uxPerspective.assessment}</p><p><b>Research context:</b> {finding.uxPerspective.researchContext}</p></section><section><small>Business analysis</small><h3>{finding.businessAnalysis.funnelStage}</h3><p><b>Impact:</b> {finding.businessAnalysis.impact}</p><p><b>KPI at risk:</b> {finding.businessAnalysis.kpi}</p><p><b>Mechanism:</b> {finding.businessAnalysis.mechanism}</p><ul>{finding.businessAnalysis.suggestions.map((s) => <li key={s}>{s}</li>)}</ul></section></div><div className={styles.recommend}><b>Recommended redesign:</b> {finding.recommendation}</div><div className={styles.screen}><header><div><small>Evidence map · {page.title}</small><h3>Original analysed screenshot</h3></div><span>{high} high priority · {page.findings.length} findings</span></header><div className={styles.canvas}><img src={page.screenshot} alt={`Original ${audit.client_name} ${page.title} screenshot`} />{page.findings.map((x, i) => { const m = x.evidence[0]?.marker; return m ? <button key={x.id} className={`${styles.marker} ${styles[colors[i % colors.length]]} ${selected === i ? styles.markerSelected : ""}`} style={{ left: `${m.x * 100}%`, top: `${m.y * 100}%` }} onClick={() => setSelected(i)}>{i + 1}</button> : null; })}</div></div></> : <div className={styles.empty}><h3>No findings on this page</h3><p>The audit did not produce a sufficiently defensible evidence-backed issue for this screenshot.</p></div>}</div></div>
    </section>}
  </main>;
}
